# Generated by Django 4.2.4 on 2023-09-02 07:43

from django.db import migrations, models
import django.db.models.deletion
import meta.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("flatpages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "flatpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flatpages.flatpage",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255, null=True, verbose_name="Description")),
                ("keywords", models.CharField(blank=True, max_length=1000, null=True, verbose_name="Keywords")),
            ],
            options={
                "verbose_name": "CMS Page",
                "verbose_name_plural": "CMS Pages",
                "db_table": "cms_page",
            },
            bases=(meta.models.ModelMeta, "flatpages.flatpage"),
        ),
    ]
